# Port name of the serial port
port_name: '/dev/ttyACM0'
# Baud rate of the serial connection
baud_rate: 115200
# PWM of the step
pwm: 50
# Time sample in milliseconds
ts: 20
# Number of step to run
nb_measure: 1
# Number of sample taken per step
nb_sample: 50
# Waiting time between each measures in milliseconds
wait_time: 1500
